// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjvaSU4v4aOQq59mo0GTJPv-Q7OCk3uhU',
    appId: '1:222545266285:web:b6b7f81eadb51fd600e164',
    messagingSenderId: '222545266285',
    projectId: 'notes-app-potofolio',
    authDomain: 'notes-app-potofolio.firebaseapp.com',
    storageBucket: 'notes-app-potofolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsPsOEqflAi6FyEdJPaQHhyyk8pCWHAX4',
    appId: '1:222545266285:android:e3ae30e8c721a81a00e164',
    messagingSenderId: '222545266285',
    projectId: 'notes-app-potofolio',
    storageBucket: 'notes-app-potofolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUyLEU4LrKdU0Hbl-znsSezYUYnb-_8Y',
    appId: '1:222545266285:ios:15e683f77401c80a00e164',
    messagingSenderId: '222545266285',
    projectId: 'notes-app-potofolio',
    storageBucket: 'notes-app-potofolio.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkUyLEU4LrKdU0Hbl-znsSezYUYnb-_8Y',
    appId: '1:222545266285:ios:15e683f77401c80a00e164',
    messagingSenderId: '222545266285',
    projectId: 'notes-app-potofolio',
    storageBucket: 'notes-app-potofolio.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjvaSU4v4aOQq59mo0GTJPv-Q7OCk3uhU',
    appId: '1:222545266285:web:e20e9551fbafac3800e164',
    messagingSenderId: '222545266285',
    projectId: 'notes-app-potofolio',
    authDomain: 'notes-app-potofolio.firebaseapp.com',
    storageBucket: 'notes-app-potofolio.firebasestorage.app',
  );
}
